import { useEffect } from "react";
import { Outlet, ScrollRestoration, isRouteErrorResponse, useLocation, useNavigate } from "react-router";
import { useTranslation } from "react-i18next";
import { Header } from "~/components/header";
import { BottomNav } from "~/components/bottom-nav";
import { AuthProvider } from "~/contexts/auth-context";
import { FeatureFlagsProvider } from "~/contexts/feature-flags-context";
import { Toaster } from "~/components/ui/sonner";
import { TooltipProvider } from "~/components/ui/tooltip";
import { isNativeApp, nativeBridge, setupNativeListeners } from "~/lib/native-bridge";
import { initLibraryRoot } from "~/lib/file-path-resolver";
import "./globals.css";

function useDarkMode() {
  useEffect(() => {
    // In native app mode, theme is controlled by the native shell via
    // window.__nativeBridge.setTheme() — skip the media query listener.
    if (isNativeApp()) return;

    const mq = window.matchMedia('(prefers-color-scheme: dark)');

    const update = () => {
      const isDark = mq.matches;
      document.documentElement.classList.toggle('dark', isDark);
      document.documentElement.style.colorScheme = isDark ? 'dark' : 'light';
    };

    update();
    mq.addEventListener('change', update);

    // Re-apply on visibility change (fixes bfcache issues on mobile)
    const handleVisibility = () => {
      if (document.visibilityState === 'visible') {
        update();
      }
    };
    document.addEventListener('visibilitychange', handleVisibility);

    return () => {
      mq.removeEventListener('change', update);
      document.removeEventListener('visibilitychange', handleVisibility);
    };
  }, []);
}

function ConditionalHeader() {
  const location = useLocation();
  // Completely hide header on share pages (public, no app chrome)
  const isSharePage = /^\/share\//.test(location.pathname);
  if (isSharePage) return null;

  // Hide header on mobile only for agent session detail (not the list page)
  const isAgentSessionDetail = /^\/agent\/[^/]+/.test(location.pathname);

  return (
    <div className={isAgentSessionDetail ? 'hidden md:block' : ''}>
      <Header />
    </div>
  );
}

function ConditionalBottomNav() {
  const location = useLocation();
  const isSharePage = /^\/share\//.test(location.pathname);
  const isAgentSessionDetail = /^\/agent\/[^/]+/.test(location.pathname);
  if (isSharePage || isAgentSessionDetail) return null;
  return <BottomNav />;
}

export default function Root() {
  useDarkMode();
  useNativeBridge();

  // Initialize library root for file path resolution
  useEffect(() => {
    initLibraryRoot()
  }, [])

  const native = isNativeApp();

  return (
    <FeatureFlagsProvider>
      <TooltipProvider>
      {/* h-dvh is the sole height constraint — do NOT add min-h-screen.
          On iOS Safari 100vh > 100dvh (vh includes the URL bar), so min-h-screen
          would make the root taller than the visible viewport, creating a competing
          scrollable layer that causes mobile scroll to jump and not follow finger. */}
      <div className={`antialiased grid grid-cols-1 grid-rows-[auto_minmax(0,1fr)] h-dvh w-full min-w-0 overflow-y-auto overflow-x-hidden${native ? ' native-app' : ''}`}>
        <AuthProvider>
          {/* Hide header in native app — the native SwiftUI shell provides navigation chrome */}
          {!native && <ConditionalHeader />}
          <main className={`min-h-0 h-full flex flex-col w-full min-w-0${native ? '' : ' row-start-2 pb-[60px] md:pb-0'}`}>
            <Outlet />
          </main>
          {!native && <ConditionalBottomNav />}
        </AuthProvider>
        <ScrollRestoration />
        <Toaster position="bottom-right" richColors closeButton />
      </div>
      </TooltipProvider>
    </FeatureFlagsProvider>
  );
}

/** Set up the Native → Web bridge listeners when running inside WKWebView. */
function useNativeBridge() {
  const navigate = useNavigate();

  useEffect(() => {
    if (!isNativeApp()) return;
    setupNativeListeners(navigate);

    // Intercept clicks on .library-file-link anchors (generated by linkifyLibraryPaths
    // in markdown/bash output). In native app, these should switch tabs via the bridge
    // instead of navigating within the current WebView.
    function handleLibraryLinkClick(e: MouseEvent) {
      const link = (e.target as HTMLElement).closest('a.library-file-link') as HTMLAnchorElement | null
      if (!link) return
      e.preventDefault()
      e.stopPropagation()
      const href = link.getAttribute('href')
      if (href) nativeBridge.navigate(href)
    }

    document.addEventListener('click', handleLibraryLinkClick, true)
    return () => {
      document.removeEventListener('click', handleLibraryLinkClick, true)
    }
  }, [navigate]);
}

export function ErrorBoundary({ error }: { error: unknown }) {
  const { t } = useTranslation('common');
  let message = t('errorBoundary.oops', 'Oops!');
  let details = t('errorBoundary.generic', 'An unexpected error occurred.');
  let stack: string | undefined;

  if (isRouteErrorResponse(error)) {
    message = error.status === 404 ? t('errorBoundary.notFoundTitle', '404') : "Error";
    details =
      error.status === 404
        ? t('errorBoundary.notFoundDetails', 'The requested page could not be found.')
        : error.statusText || details;
  } else if (import.meta.env.DEV && error && error instanceof Error) {
    details = error.message;
    stack = error.stack;
  }

  return (
    <main className="min-h-screen flex items-center justify-center p-4">
      <div className="text-center space-y-4">
        <h1 className="text-4xl font-bold">{message}</h1>
        <p className="text-muted-foreground">{details}</p>
        {stack && (
          <pre className="mt-4 p-4 bg-muted rounded-lg text-left text-xs overflow-auto max-w-2xl">
            <code>{stack}</code>
          </pre>
        )}
      </div>
    </main>
  );
}
