// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/inbox": {
    params: {};
  };
  "/inbox/:slug": {
    params: {
      "slug": string;
    };
  };
  "/library": {
    params: {};
  };
  "/library/browse": {
    params: {};
  };
  "/file/*": {
    params: {
      "*": string;
    };
  };
  "/people": {
    params: {};
  };
  "/people/:id": {
    params: {
      "id": string;
    };
  };
  "/settings": {
    params: {};
  };
  "/settings/*": {
    params: {
      "*": string;
    };
  };
  "/raw/*": {
    params: {
      "*": string;
    };
  };
  "/sqlar/*": {
    params: {
      "*": string;
    };
  };
  "/api/auth/login": {
    params: {};
  };
  "/api/auth/logout": {
    params: {};
  };
  "/api/inbox": {
    params: {};
  };
  "/api/inbox/pinned": {
    params: {};
  };
  "/api/inbox/position": {
    params: {};
  };
  "/api/inbox/:id": {
    params: {
      "id": string;
    };
  };
  "/api/inbox/:id/reenrich": {
    params: {
      "id": string;
    };
  };
  "/api/inbox/:id/status": {
    params: {
      "id": string;
    };
  };
  "/api/digest/digesters": {
    params: {};
  };
  "/api/digest/stats": {
    params: {};
  };
  "/api/digest/reset/:digester": {
    params: {
      "digester": string;
    };
  };
  "/api/digest/*": {
    params: {
      "*": string;
    };
  };
  "/api/library/file": {
    params: {};
  };
  "/api/library/file-info": {
    params: {};
  };
  "/api/library/pin": {
    params: {};
  };
  "/api/library/tree": {
    params: {};
  };
  "/api/notifications/stream": {
    params: {};
  };
  "/api/people": {
    params: {};
  };
  "/api/people/:id": {
    params: {
      "id": string;
    };
  };
  "/api/people/:id/merge": {
    params: {
      "id": string;
    };
  };
  "/api/people/embeddings/:id/assign": {
    params: {
      "id": string;
    };
  };
  "/api/people/embeddings/:id/unassign": {
    params: {
      "id": string;
    };
  };
  "/api/search": {
    params: {};
  };
  "/api/search/hybrid": {
    params: {};
  };
  "/api/search/keyword": {
    params: {};
  };
  "/api/search/semantic": {
    params: {};
  };
  "/api/settings": {
    params: {};
  };
  "/api/stats": {
    params: {};
  };
  "/api/tasks": {
    params: {};
  };
  "/api/tasks/stats": {
    params: {};
  };
  "/api/tasks/status": {
    params: {};
  };
  "/api/tasks/worker/pause": {
    params: {};
  };
  "/api/tasks/worker/resume": {
    params: {};
  };
  "/api/tasks/worker/status": {
    params: {};
  };
  "/api/tasks/:id": {
    params: {
      "id": string;
    };
  };
  "/api/upload/finalize": {
    params: {};
  };
  "/api/upload/tus": {
    params: {};
  };
  "/api/upload/tus/*": {
    params: {
      "*": string;
    };
  };
  "/api/directories": {
    params: {};
  };
  "/api/vendors/openai/models": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/inbox" | "/inbox/:slug" | "/library" | "/library/browse" | "/file/*" | "/people" | "/people/:id" | "/settings" | "/settings/*" | "/raw/*" | "/sqlar/*" | "/api/auth/login" | "/api/auth/logout" | "/api/inbox" | "/api/inbox/pinned" | "/api/inbox/position" | "/api/inbox/:id" | "/api/inbox/:id/reenrich" | "/api/inbox/:id/status" | "/api/digest/digesters" | "/api/digest/stats" | "/api/digest/reset/:digester" | "/api/digest/*" | "/api/library/file" | "/api/library/file-info" | "/api/library/pin" | "/api/library/tree" | "/api/notifications/stream" | "/api/people" | "/api/people/:id" | "/api/people/:id/merge" | "/api/people/embeddings/:id/assign" | "/api/people/embeddings/:id/unassign" | "/api/search" | "/api/search/hybrid" | "/api/search/keyword" | "/api/search/semantic" | "/api/settings" | "/api/stats" | "/api/tasks" | "/api/tasks/stats" | "/api/tasks/status" | "/api/tasks/worker/pause" | "/api/tasks/worker/resume" | "/api/tasks/worker/status" | "/api/tasks/:id" | "/api/upload/finalize" | "/api/upload/tus" | "/api/upload/tus/*" | "/api/directories" | "/api/vendors/openai/models";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/inbox.tsx": {
    id: "routes/inbox";
    page: "/inbox";
  };
  "routes/inbox.$slug.tsx": {
    id: "routes/inbox.$slug";
    page: "/inbox/:slug";
  };
  "routes/library.tsx": {
    id: "routes/library";
    page: "/library";
  };
  "routes/library.browse.tsx": {
    id: "routes/library.browse";
    page: "/library/browse";
  };
  "routes/file.$.tsx": {
    id: "routes/file.$";
    page: "/file/*";
  };
  "routes/people.tsx": {
    id: "routes/people";
    page: "/people";
  };
  "routes/people.$id.tsx": {
    id: "routes/people.$id";
    page: "/people/:id";
  };
  "routes/settings.tsx": {
    id: "routes/settings";
    page: "/settings" | "/settings/*";
  };
  "routes/raw.$.tsx": {
    id: "routes/raw.$";
    page: "/raw/*";
  };
  "routes/sqlar.$.tsx": {
    id: "routes/sqlar.$";
    page: "/sqlar/*";
  };
  "routes/api.auth.login.ts": {
    id: "routes/api.auth.login";
    page: "/api/auth/login";
  };
  "routes/api.auth.logout.ts": {
    id: "routes/api.auth.logout";
    page: "/api/auth/logout";
  };
  "routes/api.inbox.ts": {
    id: "routes/api.inbox";
    page: "/api/inbox";
  };
  "routes/api.inbox.pinned.ts": {
    id: "routes/api.inbox.pinned";
    page: "/api/inbox/pinned";
  };
  "routes/api.inbox.position.ts": {
    id: "routes/api.inbox.position";
    page: "/api/inbox/position";
  };
  "routes/api.inbox.$id.ts": {
    id: "routes/api.inbox.$id";
    page: "/api/inbox/:id";
  };
  "routes/api.inbox.$id.reenrich.ts": {
    id: "routes/api.inbox.$id.reenrich";
    page: "/api/inbox/:id/reenrich";
  };
  "routes/api.inbox.$id.status.ts": {
    id: "routes/api.inbox.$id.status";
    page: "/api/inbox/:id/status";
  };
  "routes/api.digest.digesters.ts": {
    id: "routes/api.digest.digesters";
    page: "/api/digest/digesters";
  };
  "routes/api.digest.stats.ts": {
    id: "routes/api.digest.stats";
    page: "/api/digest/stats";
  };
  "routes/api.digest.reset.$digester.ts": {
    id: "routes/api.digest.reset.$digester";
    page: "/api/digest/reset/:digester";
  };
  "routes/api.digest.$.ts": {
    id: "routes/api.digest.$";
    page: "/api/digest/*";
  };
  "routes/api.library.file.ts": {
    id: "routes/api.library.file";
    page: "/api/library/file";
  };
  "routes/api.library.file-info.ts": {
    id: "routes/api.library.file-info";
    page: "/api/library/file-info";
  };
  "routes/api.library.pin.ts": {
    id: "routes/api.library.pin";
    page: "/api/library/pin";
  };
  "routes/api.library.tree.ts": {
    id: "routes/api.library.tree";
    page: "/api/library/tree";
  };
  "routes/api.notifications.stream.ts": {
    id: "routes/api.notifications.stream";
    page: "/api/notifications/stream";
  };
  "routes/api.people.ts": {
    id: "routes/api.people";
    page: "/api/people";
  };
  "routes/api.people.$id.ts": {
    id: "routes/api.people.$id";
    page: "/api/people/:id";
  };
  "routes/api.people.$id.merge.ts": {
    id: "routes/api.people.$id.merge";
    page: "/api/people/:id/merge";
  };
  "routes/api.people.embeddings.$id.assign.ts": {
    id: "routes/api.people.embeddings.$id.assign";
    page: "/api/people/embeddings/:id/assign";
  };
  "routes/api.people.embeddings.$id.unassign.ts": {
    id: "routes/api.people.embeddings.$id.unassign";
    page: "/api/people/embeddings/:id/unassign";
  };
  "routes/api.search.ts": {
    id: "routes/api.search";
    page: "/api/search";
  };
  "routes/api.search.hybrid.ts": {
    id: "routes/api.search.hybrid";
    page: "/api/search/hybrid";
  };
  "routes/api.search.keyword.ts": {
    id: "routes/api.search.keyword";
    page: "/api/search/keyword";
  };
  "routes/api.search.semantic.ts": {
    id: "routes/api.search.semantic";
    page: "/api/search/semantic";
  };
  "routes/api.settings.ts": {
    id: "routes/api.settings";
    page: "/api/settings";
  };
  "routes/api.stats.ts": {
    id: "routes/api.stats";
    page: "/api/stats";
  };
  "routes/api.tasks.ts": {
    id: "routes/api.tasks";
    page: "/api/tasks";
  };
  "routes/api.tasks.stats.ts": {
    id: "routes/api.tasks.stats";
    page: "/api/tasks/stats";
  };
  "routes/api.tasks.status.ts": {
    id: "routes/api.tasks.status";
    page: "/api/tasks/status";
  };
  "routes/api.tasks.worker.pause.ts": {
    id: "routes/api.tasks.worker.pause";
    page: "/api/tasks/worker/pause";
  };
  "routes/api.tasks.worker.resume.ts": {
    id: "routes/api.tasks.worker.resume";
    page: "/api/tasks/worker/resume";
  };
  "routes/api.tasks.worker.status.ts": {
    id: "routes/api.tasks.worker.status";
    page: "/api/tasks/worker/status";
  };
  "routes/api.tasks.$id.ts": {
    id: "routes/api.tasks.$id";
    page: "/api/tasks/:id";
  };
  "routes/api.upload.finalize.ts": {
    id: "routes/api.upload.finalize";
    page: "/api/upload/finalize";
  };
  "routes/api.upload.tus.ts": {
    id: "routes/api.upload.tus";
    page: "/api/upload/tus" | "/api/upload/tus/*";
  };
  "routes/api.directories.ts": {
    id: "routes/api.directories";
    page: "/api/directories";
  };
  "routes/api.vendors.openai.models.ts": {
    id: "routes/api.vendors.openai.models";
    page: "/api/vendors/openai/models";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/inbox": typeof import("./app/routes/inbox.tsx");
  "routes/inbox.$slug": typeof import("./app/routes/inbox.$slug.tsx");
  "routes/library": typeof import("./app/routes/library.tsx");
  "routes/library.browse": typeof import("./app/routes/library.browse.tsx");
  "routes/file.$": typeof import("./app/routes/file.$.tsx");
  "routes/people": typeof import("./app/routes/people.tsx");
  "routes/people.$id": typeof import("./app/routes/people.$id.tsx");
  "routes/settings": typeof import("./app/routes/settings.tsx");
  "routes/raw.$": typeof import("./app/routes/raw.$.tsx");
  "routes/sqlar.$": typeof import("./app/routes/sqlar.$.tsx");
  "routes/api.auth.login": typeof import("./app/routes/api.auth.login.ts");
  "routes/api.auth.logout": typeof import("./app/routes/api.auth.logout.ts");
  "routes/api.inbox": typeof import("./app/routes/api.inbox.ts");
  "routes/api.inbox.pinned": typeof import("./app/routes/api.inbox.pinned.ts");
  "routes/api.inbox.position": typeof import("./app/routes/api.inbox.position.ts");
  "routes/api.inbox.$id": typeof import("./app/routes/api.inbox.$id.ts");
  "routes/api.inbox.$id.reenrich": typeof import("./app/routes/api.inbox.$id.reenrich.ts");
  "routes/api.inbox.$id.status": typeof import("./app/routes/api.inbox.$id.status.ts");
  "routes/api.digest.digesters": typeof import("./app/routes/api.digest.digesters.ts");
  "routes/api.digest.stats": typeof import("./app/routes/api.digest.stats.ts");
  "routes/api.digest.reset.$digester": typeof import("./app/routes/api.digest.reset.$digester.ts");
  "routes/api.digest.$": typeof import("./app/routes/api.digest.$.ts");
  "routes/api.library.file": typeof import("./app/routes/api.library.file.ts");
  "routes/api.library.file-info": typeof import("./app/routes/api.library.file-info.ts");
  "routes/api.library.pin": typeof import("./app/routes/api.library.pin.ts");
  "routes/api.library.tree": typeof import("./app/routes/api.library.tree.ts");
  "routes/api.notifications.stream": typeof import("./app/routes/api.notifications.stream.ts");
  "routes/api.people": typeof import("./app/routes/api.people.ts");
  "routes/api.people.$id": typeof import("./app/routes/api.people.$id.ts");
  "routes/api.people.$id.merge": typeof import("./app/routes/api.people.$id.merge.ts");
  "routes/api.people.embeddings.$id.assign": typeof import("./app/routes/api.people.embeddings.$id.assign.ts");
  "routes/api.people.embeddings.$id.unassign": typeof import("./app/routes/api.people.embeddings.$id.unassign.ts");
  "routes/api.search": typeof import("./app/routes/api.search.ts");
  "routes/api.search.hybrid": typeof import("./app/routes/api.search.hybrid.ts");
  "routes/api.search.keyword": typeof import("./app/routes/api.search.keyword.ts");
  "routes/api.search.semantic": typeof import("./app/routes/api.search.semantic.ts");
  "routes/api.settings": typeof import("./app/routes/api.settings.ts");
  "routes/api.stats": typeof import("./app/routes/api.stats.ts");
  "routes/api.tasks": typeof import("./app/routes/api.tasks.ts");
  "routes/api.tasks.stats": typeof import("./app/routes/api.tasks.stats.ts");
  "routes/api.tasks.status": typeof import("./app/routes/api.tasks.status.ts");
  "routes/api.tasks.worker.pause": typeof import("./app/routes/api.tasks.worker.pause.ts");
  "routes/api.tasks.worker.resume": typeof import("./app/routes/api.tasks.worker.resume.ts");
  "routes/api.tasks.worker.status": typeof import("./app/routes/api.tasks.worker.status.ts");
  "routes/api.tasks.$id": typeof import("./app/routes/api.tasks.$id.ts");
  "routes/api.upload.finalize": typeof import("./app/routes/api.upload.finalize.ts");
  "routes/api.upload.tus": typeof import("./app/routes/api.upload.tus.ts");
  "routes/api.directories": typeof import("./app/routes/api.directories.ts");
  "routes/api.vendors.openai.models": typeof import("./app/routes/api.vendors.openai.models.ts");
};