/**
 * Unified file path resolver for detecting and resolving absolute paths
 * from Claude session messages to library-relative paths.
 */
import { api } from '~/lib/api'

let libraryRoot: string | null = null

export interface ResolvedPath {
  /** The raw string found in the text */
  original: string
  /** Fully resolved absolute path */
  absolute: string
  /** Path relative to library root, or null if not a library file */
  libraryRelative: string | null
  /** true if path ends with / or has no file extension */
  isDirectory: boolean
}

/**
 * Fetch and cache the library root path. Call once on app startup.
 * Safe to call multiple times — subsequent calls return the cached value.
 */
export async function initLibraryRoot(): Promise<string | null> {
  if (libraryRoot !== null) return libraryRoot
  try {
    const res = await api.get('/api/library/root')
    if (!res.ok) return null
    const data = await res.json()
    libraryRoot = data.root
    return libraryRoot
  } catch {
    return null
  }
}

/** Get the cached library root (null if not yet initialized). */
export function getLibraryRoot(): string | null {
  return libraryRoot
}

/**
 * Resolve a single absolute path string against the library root.
 * Returns libraryRelative if the path lives inside the library, null otherwise.
 */
export function resolvePath(raw: string): ResolvedPath {
  if (!libraryRoot) {
    return { original: raw, absolute: raw, libraryRelative: null, isDirectory: false }
  }

  const absolute = raw.trim()

  // Only handle absolute paths
  if (!absolute.startsWith('/')) {
    return { original: raw, absolute, libraryRelative: null, isDirectory: false }
  }

  const isDirectory = absolute.endsWith('/') || !hasFileExtension(absolute)

  // Check if it's inside the library
  const root = libraryRoot.endsWith('/') ? libraryRoot : libraryRoot + '/'
  if (absolute.startsWith(root) || absolute === libraryRoot) {
    const relative = absolute.slice(root.length)
    return { original: raw, absolute, libraryRelative: relative, isDirectory }
  }

  return { original: raw, absolute, libraryRelative: null, isDirectory }
}

/**
 * Regex to detect absolute file paths in text.
 *
 * Matches:
 * - Absolute paths with ≥2 segments: /home/user/file.txt, /data/notes/
 *
 * Skips:
 * - URLs (http://, https://, ftp://)
 * - Single-segment paths (/tmp, /etc)
 * - Very short matches (< 4 chars)
 */
const PATH_REGEX = /(?<![a-zA-Z]:\/\/|[a-zA-Z]:|["'`([\w])\/(?:[a-zA-Z0-9_@.-]+\/)+(?:[a-zA-Z0-9_@.-]+(?:\.[a-zA-Z0-9]+)?)?/g

/**
 * Scan a block of text for absolute path strings and resolve each one.
 * Returns only paths that resolve to library files/dirs.
 */
export function extractAndResolvePaths(text: string): ResolvedPath[] {
  if (!libraryRoot) return []

  const results: ResolvedPath[] = []

  // Reset regex state
  PATH_REGEX.lastIndex = 0

  let match: RegExpExecArray | null
  while ((match = PATH_REGEX.exec(text)) !== null) {
    const raw = match[0]

    // Skip if match is inside a URL — look back to the last whitespace to catch
    // URLs where the match starts far from the "://" (e.g. matching a suffix of
    // "https://github.com/user/repo/pull/new/feature/branch-name")
    const wordStart = text.lastIndexOf(' ', match.index - 1)
    const preceding = text.slice(Math.max(0, wordStart + 1), match.index)
    if (/\w:\/\//.test(preceding)) continue

    // Skip very short matches
    if (raw.length < 4) continue

    const resolved = resolvePath(raw)
    if (resolved.libraryRelative !== null) {
      results.push(resolved)
    }
  }

  return results
}

/**
 * Generate the navigation URL for a resolved library path.
 */
export function libraryUrl(resolved: ResolvedPath): string {
  if (resolved.libraryRelative === null) return '#'
  return `/file/${resolved.libraryRelative}`
}

/**
 * Post-process an HTML string to wrap detected absolute library paths in clickable links.
 * Used for markdown-rendered content and bash output.
 *
 * Two passes:
 * 1. Strip non-URL <a href="..."> links generated by markdown (relative paths that would
 *    navigate incorrectly). Absolute library paths in href are converted to library links.
 * 2. Scan text content between tags for absolute file paths and linkify matches.
 */
export function linkifyLibraryPaths(html: string): string {
  if (!libraryRoot) return html

  // First pass: handle markdown-generated <a href="..."> links.
  // Only convert absolute paths that are in the library; strip all other non-URL links.
  let processed = html.replace(
    /<a\s[^>]*href="([^"]+)"[^>]*>([\s\S]*?)<\/a>/g,
    (_match, href: string, content: string) => {
      // Skip URLs, anchors, mailto, etc.
      if (/^(?:https?:|ftp:|mailto:|#|data:)/.test(href)) return _match
      // Skip if already a library-file-link
      if (_match.includes('library-file-link')) return _match

      // Only resolve absolute paths
      if (href.startsWith('/')) {
        const resolved = resolvePath(href)
        if (resolved.libraryRelative !== null) {
          return `<a href="${libraryUrl(resolved)}" class="library-file-link">${content}</a>`
        }
      }
      // Not an absolute library path — unwrap the <a> to avoid dead links
      return content
    }
  )

  // Second pass: linkify absolute paths in text content.
  // For plain text (no HTML tags, e.g. bash output), linkify directly.
  // For HTML, process text between tags while skipping <a>...</a> content.
  const hasHtmlTags = /<[a-zA-Z]/.test(processed)

  if (!hasHtmlTags) {
    // Plain text — linkify paths directly
    processed = linkifyInText(processed)
  } else {
    // HTML — use alternation to skip <a>...</a> content (text inside existing links
    // must not be re-linkified, e.g. URL text like "https://github.com/.../feature/x").
    processed = processed.replace(/(<a\s[^>]*>[\s\S]*?<\/a>)|(>)([^<]+)(<)/g, (_full, anchorTag: string, open: string, textContent: string, close: string) => {
      if (anchorTag) return _full
      if (!textContent.trim()) return _full

      const result = linkifyInText(textContent)
      return result === textContent ? _full : open + result + close
    })
  }

  return processed
}

// --- Internal helpers ---

/** Replace detected absolute library paths in a text string with <a> links. */
function linkifyInText(text: string): string {
  const paths = extractAndResolvePaths(text)
  if (paths.length === 0) return text

  let result = text
  // Process in reverse order of appearance to preserve string indices
  const sortedPaths = [...paths].sort((a, b) => {
    const idxA = text.indexOf(a.original)
    const idxB = text.indexOf(b.original)
    return idxB - idxA
  })

  for (const resolved of sortedPaths) {
    const idx = result.indexOf(resolved.original)
    if (idx === -1) continue
    const link = `<a href="${libraryUrl(resolved)}" class="library-file-link">${resolved.original}</a>`
    result = result.slice(0, idx) + link + result.slice(idx + resolved.original.length)
  }

  return result
}

function hasFileExtension(path: string): boolean {
  const lastSegment = path.split('/').pop() || ''
  return /\.[a-zA-Z0-9]{1,10}$/.test(lastSegment)
}
